# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JohnAdmin/Desktop/College/ECE4710/incompletelabs/lab5/lab5bpMod/lab5bpMod.srcs/sources_1/ip/Background8/Background8.xci
# IP: The module: 'Background8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JohnAdmin/Desktop/College/ECE4710/incompletelabs/lab5/lab5bpMod/lab5bpMod.gen/sources_1/ip/Background8/Background8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Background8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/JohnAdmin/Desktop/College/ECE4710/incompletelabs/lab5/lab5bpMod/lab5bpMod.srcs/sources_1/ip/Background8/Background8.xci
# IP: The module: 'Background8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JohnAdmin/Desktop/College/ECE4710/incompletelabs/lab5/lab5bpMod/lab5bpMod.gen/sources_1/ip/Background8/Background8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Background8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
