# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/conno/Downloads/lab5Complete/lab5bpModBounce/lab5bpMod/lab5bpMod.srcs/sources_1/ip/Tetris_Background_Sprite/Tetris_Background_Sprite.xci
# IP: The module: 'Tetris_Background_Sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/conno/Downloads/lab5Complete/lab5bpModBounce/lab5bpMod/lab5bpMod.gen/sources_1/ip/Tetris_Background_Sprite/Tetris_Background_Sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tetris_Background_Sprite'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/conno/Downloads/lab5Complete/lab5bpModBounce/lab5bpMod/lab5bpMod.srcs/sources_1/ip/Tetris_Background_Sprite/Tetris_Background_Sprite.xci
# IP: The module: 'Tetris_Background_Sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/conno/Downloads/lab5Complete/lab5bpModBounce/lab5bpMod/lab5bpMod.gen/sources_1/ip/Tetris_Background_Sprite/Tetris_Background_Sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Tetris_Background_Sprite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
